# Generated by Django 5.2.3 on 2025-08-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('administrator', 'Administrator'), ('employee', 'Employee')], default='client', max_length=20),
        ),
    ]
