# Generated by Django 5.2.3 on 2025-08-31 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0002_user_role'),
        ('DjangoProject', '0003_create_admin_user'),
    ]

    operations = [
    ]
