# Generated by Django 5.2.3 on 2025-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0005_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='is_available',
            new_name='availability',
        ),
        migrations.AddField(
            model_name='pizza',
            name='heading',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=20),
        ),
    ]
