# Generated by Django 5.2.3 on 2025-09-04 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0006_rename_is_available_pizza_availability_pizza_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
