# Generated by Django 5.2.3 on 2025-09-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0009_alter_pizza_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('%', 'Percentage'), ('€', 'Fixed Amount')], default='%', max_length=1)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('no_limit', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
