# Generated by Django 5.2.3 on 2025-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
