# Generated by Django 5.2.3 on 2025-10-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0013_dessert_drink_salad_sauce_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
    ]
