# Generated by Django 5.2.3 on 2025-10-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0014_remove_drink_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='description',
        ),
    ]
