# Generated by Django 5.2.3 on 2025-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0015_remove_dessert_description_remove_sauce_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='desserts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='drinks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='pizzas_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='salads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
