# Generated by Django 5.2.3 on 2025-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0016_specialoffer_desserts_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='stickers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
