# Generated by Django 5.2.3 on 2025-10-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0017_pizza_stickers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stickers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='stickers',
        ),
        migrations.AddField(
            model_name='pizza',
            name='stickers',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='DjangoProject.sticker'),
        ),
    ]
