# Generated by Django 5.2.3 on 2026-01-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0021_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='ilievpetarbt8@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approved',
            field=models.CharField(choices=[('Not Approved', 'Not Approved'), ('Approved', 'Approved')], default='Not Approved', max_length=20),
        ),
    ]
